
// This file has been generated by the GUI designer. Do not modify.
namespace VrayMat2Blender
{
	public partial class About
	{
		private global::Gtk.DrawingArea drawingarea1;
		private global::Gtk.Button button22;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VrayMat2Blender.About
			this.WidthRequest = 450;
			this.HeightRequest = 300;
			this.Name = "VrayMat2Blender.About";
			this.Title = global::Mono.Unix.Catalog.GetString ("About");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-about", global::Gtk.IconSize.Menu);
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			this.DefaultWidth = 450;
			this.DefaultHeight = 300;
			this.Decorated = false;
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Internal child VrayMat2Blender.About.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.drawingarea1 = new global::Gtk.DrawingArea ();
			this.drawingarea1.Name = "drawingarea1";
			w1.Add (this.drawingarea1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(w1 [this.drawingarea1]));
			w2.Position = 0;
			// Internal child VrayMat2Blender.About.ActionArea
			global::Gtk.HButtonBox w3 = this.ActionArea;
			w3.Name = "__gtksharp_79_Stetic_TopLevelDialog_ActionArea";
			// Container child __gtksharp_79_Stetic_TopLevelDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button22 = new global::Gtk.Button ();
			this.button22.CanFocus = true;
			this.button22.Name = "button22";
			this.button22.UseUnderline = true;
			this.button22.Label = global::Mono.Unix.Catalog.GetString ("OK");
			this.AddActionWidget (this.button22, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w4 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w3 [this.button22]));
			w4.Expand = false;
			w4.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
